FROM python:3.10-slim

WORKDIR /app
RUN pip install --no-cache-dir fastapi uvicorn python-multipart

COPY ./scripts/fileserver_app.py /app/fileserver_app.py

EXPOSE 8000
CMD ["uvicorn", "fileserver_app:app", "--host", "0.0.0.0", "--port", "8000"]
